FROM apache/airflow:2.8.1

# Airflow needs this to authenticate to BigQuery and GCS
# COPY ./creds/* ./creds/

RUN pip install --user --upgrade pip
RUN pip install --no-cache-dir --user requests==2.31.0 pyarrow==15.0.0 \
                                      pandas==2.0.3
RUN pip install 'apache-airflow[google]'